admin_category_index:
    path:     /
    defaults: { _controller: "PixelpromiCMSBundle:Category:index" }
    methods:  GET

admin_category_show:
    path:     /{id}/show
    defaults: { _controller: "PixelpromiCMSBundle:Category:show" }
    methods:  GET

admin_category_new:
    path:     /new
    defaults: { _controller: "PixelpromiCMSBundle:Category:new" }
    methods:  [GET, POST]

admin_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "PixelpromiCMSBundle:Category:edit" }
    methods:  [GET, POST]

admin_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "PixelpromiCMSBundle:Category:delete" }
    methods:  DELETE
