admin_post_index:
    path:     /
    defaults: { _controller: "PixelpromiCMSBundle:Post:index" }
    methods:  GET

admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "PixelpromiCMSBundle:Post:show" }
    methods:  GET

admin_post_new:
    path:     /new
    defaults: { _controller: "PixelpromiCMSBundle:Post:new" }
    methods:  [GET, POST]

admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "PixelpromiCMSBundle:Post:edit" }
    methods:  [GET, POST]

admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "PixelpromiCMSBundle:Post:delete" }
    methods:  DELETE
